universe = docker
docker_image = blakshana/interformer:latest

# Change train/test accordingly
executable = condor/sh/interformer_preprocessing_valset.sh
output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue