import csv
import re
from pathlib import Path

"""
This script parses the CNNaffinity and CNNpose_score values from each complex and compiles it into a single CSV. 
"""

def parse_gnina_sdf_scores(sdf_file: Path):
    """
    This function reads the full SDF text and searches for multiple possible name variants, so that GNINA naming conventions can still be visible.
    Uses argument of sdf_file as SDF output file, and returns a tuple containing all parsed CNN pose score and CNN affinity score values.
    """
    text = sdf_file.read_text(errors="ignore")

    pose_scores = []
    affinity_scores = []

    #Including multiple labels used in GNINA SDF files for flexibility
    score_patterns = ["CNNscore", "CNN_score", "CNN_pose_score", "CNN Pose Score", "CNN pose score"]
    affinity_patterns = ["CNNaffinity", "CNN_affinity", "CNN Affinity", "CNN affinity"]

    #Extracting floating-point values in SDF property tags
    # Use regex expressions for more flexibility
    for pattern in score_patterns:
        matches = re.findall(rf">\s*<\s*{re.escape(pattern)}\s*>\s*\n([-\d.eE]+)", text)
        pose_scores.extend(float(x) for x in matches)

    for pattern in affinity_patterns:
        matches = re.findall(rf">\s*<\s*{re.escape(pattern)}\s*>\s*\n([-\d.eE]+)", text)
        affinity_scores.extend(float(x) for x in matches)

    return pose_scores, affinity_scores


def collect_metrics(model_name: str, model_dir: Path):
    
    """
    This function gathers all CNN pose scores, and CNN affinity scores from the .sdf files in the dir. Then results are stored as a list of dictionaries.

    """
        
    rows = []

    for pred_sdf in sorted(model_dir.glob("*.sdf")):

        pose_scores, affinity_scores = parse_gnina_sdf_scores(pred_sdf)

        rows.append(
            {
                "model": model_name,
                "complex_id": pred_sdf.stem.replace("_pred", ""),
                "best_cnn_pose_score": pose_scores[0] if pose_scores else None,
                "best_cnn_affinity": affinity_scores[0] if affinity_scores else None,
                "num_poses": max(len(pose_scores), len(affinity_scores)),
            }
        )

    return rows

def write_metrics_csv(rows, out_csv: Path):
    """
    Function to extract collected docking metrics to a CSV file. Uses rows generated by 'collect_metrics' and output CSV file path (out_csv).
    This is so that we can view the metrics better, as a reader, in the dir of each model. 
    """
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "model",
        "complex_id",
        "best_cnn_pose_score",
        "best_cnn_affinity",
        "num_poses",
    ]

    with out_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

def main():

    results_root = Path("results_posebusters_redocking")

    for model_name in ["dense_seed1", "default2018_seed1"]:

        model_dir = results_root / model_name

        rows = collect_metrics(model_name, model_dir)

        output_csv = results_root / model_name / f"{model_name}_metrics.csv"

        write_metrics_csv(rows, output_csv)

        print(f"Wrote {len(rows)} rows to {output_csv}")

if __name__ == "__main__":
    main()