universe                = docker
docker_image            = docker.io/ansc00053/gnina-train:kd2
executable              = /bin/bash
arguments               = redocking_posebusters.sh
output                  = runlogs/gnina_redocking.$(ClusterId).$(ProcId).out
error                   = runlogs/gnina_redocking.$(ClusterId).$(ProcId).err
log                     = runlogs/gnina_redocking.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = redocking_posebusters.sh, posebusters_redocking.py, posebusters_filtered.tar.gz, retrained_checkpoints.tar.gz
transfer_output_files   = results/posebusters_redocked, results_posebusters_redocking.tar.gz
request_GPUs            = 1
request_CPUs            = 8
request_memory          = 32G
request_disk            = 30G
requirements            = UidDomain == "cs.uni-saarland.de"
getenv                  = HOME
+WantGPUHomeMounted     = true
queue 1