universe                = docker
docker_image            = docker.io/ansc00053/gnina-train:proto-v2
executable              = /bin/bash
arguments               = run_gnina.sh
output                  = runlogs/gnina_proto.$(ClusterId).$(ProcId).out
error                   = runlogs/gnina_proto.$(ClusterId).$(ProcId).err
log                     = runlogs/gnina_proto.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = run_gnina.sh, run_proto_gnina.py, prototype_data.tar.gz
transfer_output_files   = results, data/proto_train.types
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 8G
request_disk            = 30G
requirements            = UidDomain == "cs.uni-saarland.de"
getenv                  = HOME
+WantGPUHomeMounted     = true
queue 1
