universe = docker
docker_image = blakshana/interformer:v4
# Change according to model:
# interformer_affinity_pose_model, interformer_energy_model, interformer_affinity_normal
executable = interformer_energy_model.sh
output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs =  4
request_memory = 64G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue