universe = docker
docker_image = blakshana/interformer:v6
# input the checkpoints and relevant files
# for complex and gaussian prediction result
transfer_input_files = interformer, data, lightning_logs, interformer_affinity_pose_final_test.sh
executable = interformer_affinity_pose_final_test.sh

output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = result/
request_GPUs = 1
request_CPUs = 8
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue