universe = docker
docker_image = blakshana/interformer:latest
executable = start.sh
output = logs/interformer.$(ClusterId).$(ProcId).out
error = logs/interformer.$(ClusterId).$(ProcId).err
log = logs/interformer.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue