universe = docker
docker_image = blakshana/interformer:v2
executable = interformer_models.sh
output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue