# HTCondor_Submit_File
universe                = docker
docker_image            = docker.io/adla00004/nnti_project:baseline
executable              = task3_analysis.sh
arguments               = $(Process)

# Resources
request_gpus            = 1
request_cpus            = 4
request_memory          = 16G

# Requirements: Matches your baseline setup
requirements            = (Target.HasDocker == True) && (Target.GPUs > 0)

# Mounting (Crucial to see your project files)
+WantScratchMounted     = true
+WantGPUHomeMounted     = true

error = task3_analysis.err
output = task3_analysis.out
log = task3_analysis.log

queue 1
