adamw: false
all_atoms: true
asyncronous_noise_schedule: false
atom_max_neighbors: 8
batch_size: 2
c_alpha_max_neighbors: 24
cache_path: .cache/data
chain_cutoff: 10
compare_true_protein: false
confidence_dropout: 0.0
confidence_no_batchnorm: false
confidence_weight: 0.33
config: null
conformer_match_score: dist
conformer_match_sidechains: false
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: false
data_dir: data/PDBBIND_atomCorrected/
dataloader_drop_last: false
device: !!python/object/apply:torch.device
- cuda
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: null
flexdist: 3.5
flexdist_distance_metric: prism
flexible_sidechains: true
high_confidence_threshold: 5.0
include_confidence_prediction: false
include_miscellaneous_atoms: false
inf_pocket_cutoff: 5
inf_pocket_knowledge: false
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
limit_complexes: 0
log_dir: /home/bdldt_team003/DiffDock-Pocket/workdir
lr: 0.001
match_max_rmsd: 2.0
match_protein_file: protein_processed_fix
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
multiplicity: 1
n_epochs: 3
no_aminoacid_identities: false
no_batch_norm: false
no_torsion: false
norm_by_sigma: false
not_fixed_center_conv: false
not_fixed_knn_radius_graph: false
not_full_dataset: false
not_knn_only_graph: false
ns: 60
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 1
num_inference_complexes: 100
num_workers: 1
nv: 10
odd_parity: false
pin_memory: false
pocket_buffer: 10.0
pocket_cutoff: 5
pocket_mode_graph: false
pocket_reduction: true
pocket_reduction_mode: center-dist
project: ligbind_tr
protein_file: protein_processed
protein_ligand_csv: /home/bdldt_team003/DiffDock-Pocket/training_input.csv
receptor_radius: 15.0
remove_hs: true
restart_dir: null
restart_lr: null
rot_alpha: 1.0
rot_beta: 1.0
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.25
run_name: prototype_training
sampling_alpha: 1.0
sampling_beta: 1.0
sc_tor_weight: 0.25
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
separate_noise_schedule: false
sh_lmax: 1
sidechain_tor_alpha: 1
sidechain_tor_beta: 1
sidechain_tor_sigma_max: 3.14
sidechain_tor_sigma_min: 0.03
sigma_embed_dim: 64
skip_no_pocket_atoms: false
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: /home/bdldt_team003/DiffDock-Pocket/proto_split_train.txt
split_val: /home/bdldt_team003/DiffDock-Pocket/proto_split_val.txt
test_sigma_intervals: false
tor_alpha: 1.0
tor_beta: 1.0
tor_sigma_max: 3.14
tor_sigma_min: 0.03
tor_weight: 0.25
tr_only_confidence: true
tr_sigma_max: 5.0
tr_sigma_min: 0.1
tr_weight: 0.25
train_inference_freq: null
use_ema: true
use_full_size_protein_file: false
use_old_atom_encoder: false
use_old_wrong_embedding_order: false
use_original_conformer: false
use_original_conformer_fallback: true
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: false
