universe = docker
docker_image = docker.io/elab00003/unimol:1
executable = /home/bdldt_team007/DLDockingBenchSeminar/run_check_lmdb.sh
output = /home/bdldt_team007/DLDockingBenchSeminar/logs/check_lmdb.out
error  = /home/bdldt_team007/DLDockingBenchSeminar/logs/check_lmdb.err
log    = /home/bdldt_team007/DLDockingBenchSeminar/logs/check_lmdb.log
should_transfer_files = NO
request_GPUs = 0
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
