universe = docker
docker_image = docker.io/elab00003/unimol:1
executable = /home/bdldt_team007/DLDockingBenchSeminar/run_gen_posebusters_csv.sh
output = /home/bdldt_team007/DLDockingBenchSeminar/logs/gen_posebusters_csv.out
error  = /home/bdldt_team007/DLDockingBenchSeminar/logs/gen_posebusters_csv.err
log    = /home/bdldt_team007/DLDockingBenchSeminar/logs/gen_posebusters_csv.log
should_transfer_files = NO
request_GPUs = 0
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
