_wandb:
    value:
        cli_version: 0.27.2
        e:
            db62y3l0sthkgxyyuchbs17xxpt4c7q4:
                args:
                    - -data_path
                    - data/proto_train_val_final.csv
                    - -work_path
                    - data/proto_train
                    - -ligand
                    - ligand/rcsb
                    - -seed
                    - "1111"
                    - -filter_type
                    - normal
                    - -native_sampler
                    - "0"
                    - -Code
                    - Energy
                    - -batch_size
                    - "4"
                    - -gpus
                    - "1"
                    - -method
                    - Gnina2
                    - -patience
                    - "30"
                    - -early_stop_metric
                    - val_loss
                    - -early_stop_mode
                    - min
                    - -affinity_pre
                    - -run_name
                    - Energy_model_full_data
                    - --warmup_updates
                    - "11000"
                    - --peak_lr
                    - "0.0012"
                    - --n_layers
                    - "6"
                    - --hidden_dim
                    - "128"
                    - --num_heads
                    - "8"
                    - --dropout_rate
                    - "0.1"
                    - --attention_dropout_rate
                    - "0.1"
                    - --weight_decay
                    - "1e-5"
                    - --energy_mode
                    - "True"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "12700431884288"
                        used: "139415638016"
                email: beho00003@uni-saarland.de
                executable: /main/home/mambaforge/bin/python3
                git:
                    commit: aff61c182dbdab1c954ef45e252f0eeb3401b19f
                    remote: git@github.com:volkamerlab/DLDockingBenchSeminar.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-5f1a1bda-15b3-9698-57a5-a20251d368c5
                host: bdldt_team001-169001.0-gefjon.hpc.uni-saarland.de
                memory:
                    total: "1081982521344"
                os: Linux-5.15.0-177-generic-x86_64-with-glibc2.35
                program: /home/bdldt_team001/DLDockingBenchSeminar/train.py
                python: CPython 3.12.5
                root: .
                startedAt: "2026-06-28T07:21:33.940008Z"
                writerId: db62y3l0sthkgxyyuchbs17xxpt4c7q4
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 53
                - 103
            "3":
                - 7
                - 13
                - 15
                - 41
                - 66
            "4": 3.12.5
            "5": 0.27.2
            "12": 0.27.2
            "13": linux-x86_64
args:
    value:
        Code: Energy
        affinity_pre: true
        angle_feat_size: 0
        attention_dropout_rate: 0.1
        attention_kd: 0
        attention_mask: true
        batch_size: 4
        checkpoint: ./
        clip: 5
        complex_to_data: feats.gnina_types.gnina_featurizer.obabel_mol_parser
        data_path: data/proto_train_val_final.csv
        dataset: sbdd
        debug: false
        dropout_rate: 0.1
        early_stop_metric: val_loss
        early_stop_mode: min
        edge_feat_size: 1
        edge_featurizer: <feats.gnina_types.gnina_featurizer.PLIPEdgeFeaturizer object at 0x7f8620b1bf20>
        edge_output_layer: true
        end_lr: 1e-09
        energy_mode: true
        energy_output_folder: ""
        ensemble:
            - checkpoint
        exp: Interformer_Gnina2
        ffn_scale: 4
        filter_type: normal
        gpus: 1
        hidden_dim: 128
        inference: false
        inter_encoder: true
        intput_dropout_rate: 0
        intra_encoder: true
        jizhi: false
        ligand_folder: ligand/rcsb
        main_loop: 1
        method: Gnina2
        metric_name:
            - r
        model: Interformer
        n_jobs: 70
        n_layers: 6
        native_sampler: 0
        neg_weight: 1
        node_feat_size: 1
        node_featurizer: <feats.gnina_types.gnina_featurizer.PLIPAtomFeaturizer object at 0x7f8620b1bef0>
        num_epochs: 2000
        num_gpus: 8
        num_heads: 8
        num_nodes: 1
        patience: 30
        peak_lr: 0.0012
        per_target: false
        per_target_sampler: 0
        pocket_path: pocket
        pose_sel_mode: false
        posfix: '*val_loss*'
        precision: 16
        rbf_K: 128
        rbf_cutoff: 10
        reload: true
        run_name: Energy_model_full_data
        seed: 1111
        split_folder: diffdock_splits
        target_wise_sampler: 0
        test_csv:
            - ./test.csv
        uff_as_ligand: false
        use_ff_ligands: uff
        use_mid: false
        vs: false
        warmup_updates: 11000
        weight_decay: 1e-05
        work_path: data/proto_train
        worker: 8
batch_size:
    value: 4
data_path:
    value: data/proto_train_val_final.csv
learning_rate:
    value: N/A
model:
    value: Interformer
num_epochs:
    value: 2000
precision:
    value: 16
