universe = docker
docker_image = docker.io/dhanya24/diffdock-pocket-fixed:v8

executable = /home/bdldt_team003/DiffDock-Pocket/run_inference.sh

output = /home/bdldt_team003/DiffDock-Pocket/logs/inference.out
error  = /home/bdldt_team003/DiffDock-Pocket/logs/inference.err
log    = /home/bdldt_team003/DiffDock-Pocket/logs/inference.log

request_GPUs   = 1
request_CPUs   = 4
request_memory = 32GB
request_disk   = 20GB

requirements = (UidDomain == "cs.uni-saarland.de") && (TARGET.CUDACapability >= 3.5)
+WantGPUHomeMounted = true
+WantGPULab = true

queue
