universe = docker
docker_image = blakshana/interformer:v6
# input the checkpoints and relevant files
# for complex and gaussian prediction result
transfer_input_files = interformer, data, checkpoints
executable = condor-workflow/step5/interformer_affinity_pose_test_data.sh

output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = ""
request_GPUs = 1
request_CPUs = 16
request_memory = 32G
requirements = (Target.CUDADeviceName == "NVIDIA A100-SXM4-40GB") || (Target.CUDADeviceName == "NVIDIA A100-PCIE-40GB") || (Target.CUDADeviceName == "NVIDIA A100-SXM4-80GB") || (Target.CUDADeviceName == "NVIDIA A100-PCIE-80GB")
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue