universe = docker
docker_image = blakshana/interformer:v6
# input the checkpoints and relevant files
# for .csv file for affinity and pose model training
transfer_input_files = docking, dock_results, condor-workflow/step4/interformer_affinity_pose_docking.sh
# data/proto_train_val_final.csv (Next step)
executable = condor-workflow/step4/interformer_affinity_pose_docking.sh

# Initially had output = "" but it produced no output.
output = logs/josh-interformer.$(ClusterId).$(ProcId).out
error = logs/josh-interformer.$(ClusterId).$(ProcId).err
log = logs/josh-interformer.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = dock_results/energy_train/
# data/proto_train_val_final.round0.csv (Next step)

request_GPUs = 1
request_CPUs = 16
request_memory = 64G
request_disk = 300G
requirements = (Target.CUDADeviceName == "NVIDIA A100-SXM4-40GB") || (Target.CUDADeviceName == "NVIDIA A100-PCIE-40GB") || (Target.CUDADeviceName == "NVIDIA A100-SXM4-80GB") || (Target.CUDADeviceName == "NVIDIA A100-PCIE-80GB")
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
# +WantScratchMounted = true 
queue