#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
train.py - Retraining / fine-tuning loop for KarmaDock.

The model's own forward pass already returns the two training losses:

    rmsd_loss, mdn_loss = model(data, device, pos_r)      # see KarmaDock_architecture.py
    loss = pos_r * rmsd_loss + mdn_loss                   # see utils/fns.karmadock_evaluation

This script wraps those into a complete, checkpointed training loop.

Two modes (same script):
  * from scratch :  --init_model ""                 (random init)
  * fine-tune    :  --init_model /app/KarmaDock/trained_models/karmadock_screening.pkl

Single GPU - the cluster only provides 1 GPU per job :( It expects graphs
already generated by KarmaDock's generate_graph.py (one <complex_id>.dgl file per
complex in --graph_dir). 
"""

import argparse
import os
import time

import numpy as np
import torch
import torch.nn as nn

# --- KarmaDock modules ---
from utils.fns import set_random_seed, Early_stopper, karmadock_evaluation
from dataset.graph_obj import PDBBindGraphDataset
from dataset.dataloader_obj import PassNoneDataLoader
from architecture.KarmaDock_architecture import KarmaDock

# --- local (scripts/) ---
from seminar_csv import complex_ids


def parse_args():
    p = argparse.ArgumentParser(description="Retrain / fine-tune KarmaDock.")
    p.add_argument("--graph_dir", required=True,
                   help="Dir with per-complex <id>.dgl graphs (from generate_graph.py).")
    p.add_argument("--val_graph_dir", default="",
                   help="Graph dir for the validation complexes when --val_csv points to a "
                        "separately-preprocessed split (LP train/val live in different dirs). "
                        "Defaults to --graph_dir.")
    p.add_argument("--complex_dir", default="",
                   help="KarmaDock-layout complex dir (only needed if a graph must be regenerated).")
    p.add_argument("--csv", required=True,
                   help="Seminar train CSV (proto_train.csv / full_train.csv / lp_train.csv).")
    p.add_argument("--val_csv", default="",
                   help="Optional explicit validation CSV. If set, ALL of --csv is used "
                        "for training and these complexes for validation -- used for "
                        "LP-PDBBind, whose leak-proof val split must NOT be a random "
                        "carve-out of train. If empty, fall back to a --val_frac split.")
    p.add_argument("--out_dir", required=True,
                   help="Where to write checkpoints and the training log.")
    p.add_argument("--init_model", default="",
                   help="Checkpoint to initialise from. Empty = train from scratch; "
                        "set to karmadock_screening.pkl to fine-tune.")
    p.add_argument("--resume", action="store_true",
                   help="Resume from <out_dir>/last.pt if present (for cluster reschedules).")
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--batch_size", type=int, default=16,
                   help="Physical minibatch size (limited by GPU memory).")
    p.add_argument("--accum_steps", type=int, default=1,
                   help="Gradient-accumulation steps. Effective batch = batch_size*accum_steps. "
                        "Paper uses an effective batch of 64; on a 16 GB V100 use e.g. "
                        "--batch_size 8 --accum_steps 8.")
    p.add_argument("--lr", type=float, default=5e-4)
    p.add_argument("--weight_decay", type=float, default=0.0)
    p.add_argument("--pos_r", type=float, default=1.0,
                   help="Weight on the pose (RMSD) loss vs the MDN scoring loss.")
    p.add_argument("--val_frac", type=float, default=0.1)
    p.add_argument("--patience", type=int, default=20,
                   help="Early-stopping patience (epochs without val improvement).")
    p.add_argument("--num_workers", type=int, default=4)
    p.add_argument("--random_seed", type=int, default=2023)
    p.add_argument("--grad_clip", type=float, default=10.0)
    p.add_argument("--jitter", type=float, default=0.0,
                   help="Scale of coordinate jittering (std in Å) for training augmentation.")
    # Weights & Biases. Key comes from the WANDB_API_KEY env var, never a flag.
    p.add_argument("--wandb", action="store_true", help="log metrics to W&B")
    p.add_argument("--wandb_project", default="karmadock-seminar")
    p.add_argument("--wandb_entity", default=None, help="W&B team/user (optional)")
    p.add_argument("--wandb_run_name", default=None)
    return p.parse_args()


def split_available(ids, graph_dir, val_frac, seed):
    """Keep only ids that actually have a graph, then deterministically split."""
    have = [i for i in ids if os.path.exists(os.path.join(graph_dir, f"{i}.dgl"))]
    missing = len(ids) - len(have)
    if missing:
        print(f"# WARNING: {missing}/{len(ids)} complexes have no .dgl graph "
              f"(rdkit/pocket failures) and are skipped.")
    rng = np.random.RandomState(seed)
    perm = rng.permutation(len(have))
    n_val = max(1, int(round(len(have) * val_frac)))
    val_idx = set(perm[:n_val].tolist())
    train_ids = [have[i] for i in range(len(have)) if i not in val_idx]
    valid_ids = [have[i] for i in range(len(have)) if i in val_idx]
    return train_ids, valid_ids


def available(ids, graph_dir):
    """Keep only ids that actually have a .dgl graph (used with an explicit val CSV)."""
    have = [i for i in ids if os.path.exists(os.path.join(graph_dir, f"{i}.dgl"))]
    missing = len(ids) - len(have)
    if missing:
        print(f"# WARNING: {missing}/{len(ids)} complexes have no .dgl graph and are skipped.")
    return have


def build_loader(ids, args, dataset_type, shuffle, graph_dir=None):
    ds = PDBBindGraphDataset(
        src_dir=args.complex_dir,
        pdb_ids=ids,
        dst_dir=graph_dir or args.graph_dir,
        dataset_type=dataset_type,
        n_job=1,
        on_the_fly=True,   # reload each <id>.dgl and re-randomise the start pose per epoch
        verbose=False,
    )
    return PassNoneDataLoader(
        dataset=ds, batch_size=args.batch_size, shuffle=shuffle,
        num_workers=args.num_workers, follow_batch=[], pin_memory=True,
    )


def main():
    args = parse_args()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(args.out_dir, exist_ok=True)
    set_random_seed(args.random_seed)
    print(f"# device: {device}")

    # ---- Weights & Biases ----
    wb = None
    if args.wandb:
        try:
            import wandb
            # Credentials come from WANDB_API_KEY or a one-time `wandb login` (~/.netrc, visible
            # in the job via the mounted home). Only force offline if neither is present; then
            # `wandb sync <dir>` later from a node that has internet.
            has_creds = os.environ.get("WANDB_API_KEY") or os.path.exists(os.path.expanduser("~/.netrc"))
            if not has_creds and os.environ.get("WANDB_MODE") != "offline":
                print("# WARNING: no W&B credentials (WANDB_API_KEY / ~/.netrc) -> forcing offline")
                os.environ["WANDB_MODE"] = "offline"
            eff_batch = args.batch_size * args.accum_steps
            stage = "scoring" if args.pos_r == 0 else "docking"
            base = args.wandb_run_name or "kd"
            # W&B run identity.
            rid_file = os.path.join(args.out_dir, "wandb_run_id.txt")
            if args.resume and os.path.exists(os.path.join(args.out_dir, "last.pt")) and os.path.exists(rid_file):
                run_id = open(rid_file).read().strip()
            else:
                run_id = f"{base}_{int(time.time())}_{os.getpid()}"
                with open(rid_file, "w") as _rf:
                    _rf.write(run_id)
            # readable start-time stamp from the persisted run_id (stable across --resume),
            # so every fresh run gets a unique, human-readable name instead of a reused PID.
            stamp = time.strftime('%Y%m%d-%H%M%S', time.localtime(int(run_id.rsplit('_', 2)[1])))
            run_name = (f"{base}_lr{args.lr:g}_bs{eff_batch}_ep{args.epochs}"
                        f"_pat{args.patience}_seed{args.random_seed}_{stamp}")
            cfg = dict(vars(args))
            cfg.update(effective_batch=eff_batch, stage=stage,
                       init_from=("scratch" if not args.init_model else os.path.basename(args.init_model)))
            wb = wandb.init(project=args.wandb_project, entity=args.wandb_entity,
                            id=run_id, name=run_name, config=cfg,
                            dir=args.out_dir, resume="allow")
            print(f"# W&B run: {run_name}")
        except Exception as e:
            print(f"# WARNING: W&B disabled ({e})")
            wb = None

    # ---- data ----
    # If --val_csv is given, use it verbatim as the validation set and ALL of
    # --csv for training.
    val_graph_dir = args.val_graph_dir or args.graph_dir
    if args.val_csv:
        train_ids = available(complex_ids(args.csv), args.graph_dir)
        valid_ids = available(complex_ids(args.val_csv), val_graph_dir)
    else:
        train_ids, valid_ids = split_available(
            complex_ids(args.csv), args.graph_dir, args.val_frac, args.random_seed)
    print(f"# train: {len(train_ids)} | valid: {len(valid_ids)} complexes")
    train_loader = build_loader(train_ids, args, "train", shuffle=True)
    valid_loader = build_loader(valid_ids, args, "valid", shuffle=False, graph_dir=val_graph_dir)

    # ---- model ----
    # DataParallel stores params under a 'module.' prefix, so the checkpoint format matches
    # the P2/P3 checkpoints that inference (ligand_docking.py) already reads.
    model = KarmaDock()
    model = nn.DataParallel(model, device_ids=[0] if device.startswith("cuda") else None)
    model.to(device)
    if args.init_model:
        print(f"# init weights from {args.init_model}")
        state = torch.load(args.init_model, map_location=device)
        model.load_state_dict(state["model_state_dict"], strict=False)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr,
                                 weight_decay=args.weight_decay)

    best_ckpt = os.path.join(args.out_dir, "karmadock_team002.pkl")
    last_ckpt = os.path.join(args.out_dir, "last.pt")
    stopper = Early_stopper(model_file=best_ckpt, mode="lower", patience=args.patience)
    best_val = None

    start_epoch = 0
    if args.resume and os.path.exists(last_ckpt):
        ck = torch.load(last_ckpt, map_location=device)
        model.load_state_dict(ck["model_state_dict"], strict=True)
        optimizer.load_state_dict(ck["optimizer_state_dict"])
        start_epoch = ck["epoch"] + 1
        best_val = ck.get("best_score", None)
        stopper.best_score = best_val
        print(f"# resumed from {last_ckpt} at epoch {start_epoch}")

    log_path = os.path.join(args.out_dir, "train_log.csv")
    if start_epoch == 0:
        with open(log_path, "w") as f:
            f.write("epoch,train_loss,train_rmsd,train_mdn,val_loss,val_rmsd,val_mdn,seconds\n")

    # ---- training loop ----
    for epoch in range(start_epoch, args.epochs):
        t0 = time.perf_counter()
        model.train()
        tr_tot, tr_rmsd, tr_mdn, n = 0.0, 0.0, 0.0, 0
        optimizer.zero_grad()
        accum = 0
        for data in train_loader:
            if data is None:
                continue
            data = data.to(device)
            if args.jitter > 0.0:
                pos = data['ligand'].pos
                noise = torch.randn_like(pos) * args.jitter
                data['ligand'].pos = pos + noise
            rmsd_loss, mdn_loss = model(data, device, args.pos_r)
            if mdn_loss is None:
                continue
            loss = args.pos_r * rmsd_loss + mdn_loss
            (loss / args.accum_steps).backward()
            accum += 1
            if accum % args.accum_steps == 0:
                if args.grad_clip > 0:
                    nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                optimizer.step()
                optimizer.zero_grad()
            tr_tot += float(loss); tr_rmsd += float(rmsd_loss); tr_mdn += float(mdn_loss); n += 1
        if accum % args.accum_steps != 0:
            if args.grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()
            optimizer.zero_grad()

        # ---- validation ----
        n = max(n, 1)
        tr_tot, tr_rmsd, tr_mdn = tr_tot / n, tr_rmsd / n, tr_mdn / n
        v_tot, v_rmsd, v_mdn = karmadock_evaluation(model, valid_loader, device, args.pos_r)
        val_loss = float(v_tot.mean()); val_rmsd = float(v_rmsd.mean()); val_mdn = float(v_mdn.mean())
        secs = time.perf_counter() - t0

        print(f"[epoch {epoch:03d}] train {tr_tot:.3f} (rmsd {tr_rmsd:.3f}/mdn {tr_mdn:.3f}) | "
              f"val {val_loss:.3f} (rmsd {val_rmsd:.3f}/mdn {val_mdn:.3f}) | {secs:.0f}s")
        with open(log_path, "a") as f:
            f.write(f"{epoch},{tr_tot:.5f},{tr_rmsd:.5f},{tr_mdn:.5f},"
                    f"{val_loss:.5f},{val_rmsd:.5f},{val_mdn:.5f},{secs:.1f}\n")
        if wb is not None:
            wb.log({"epoch": epoch, "lr": optimizer.param_groups[0]["lr"],
                    "train/loss": tr_tot, "train/rmsd": tr_rmsd, "train/mdn": tr_mdn,
                    "val/loss": val_loss, "val/rmsd": val_rmsd, "val/mdn": val_mdn,
                    "epoch_seconds": secs}, step=epoch)

        # ---- checkpoint + early stopping ----
        stopper.step(val_loss, model)
        best_val = stopper.best_score
        torch.save({"epoch": epoch,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "best_score": stopper.best_score}, last_ckpt)
        if stopper.early_stop:
            print(f"# early stopping at epoch {epoch}")
            break

    if wb is not None:
        wb.summary["best_val_loss"] = float(best_val) if best_val is not None else None
        try:
            art = __import__("wandb").Artifact("karmadock_team002", type="model")
            art.add_file(best_ckpt)
            wb.log_artifact(art)
        except Exception as e:
            print(f"# W&B artifact upload skipped ({e})")
        wb.finish()
    print(f"# done. best checkpoint: {best_ckpt}")


if __name__ == "__main__":
    main()
