#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
train.py - Retraining / fine-tuning loop for KarmaDock (BDLDT seminar, team002).

KarmaDock's public repo ships inference code + pretrained weights only; it does
NOT include a training script. However the model's own forward pass already
returns the two training losses:

    rmsd_loss, mdn_loss = model(data, device, pos_r)      # see KarmaDock_architecture.py
    loss = pos_r * rmsd_loss + mdn_loss                   # see utils/fns.karmadock_evaluation

This script wraps those into a complete, checkpointed training loop so we can
produce our OWN training checkpoint as required by the prototype submission.

Two modes (same script):
  * from scratch :  --init_model ""                 (random init)
  * fine-tune    :  --init_model /app/KarmaDock/trained_models/karmadock_screening.pkl

It expects graphs already generated by KarmaDock's generate_graph.py
(one <complex_id>.dgl file per complex in --graph_dir). Train/valid split is
derived deterministically from the seminar CSV.

Run inside the project Docker image, where /app/KarmaDock is on PYTHONPATH.
"""

import argparse
import contextlib
import os
import sys
import time

import numpy as np
import torch
import torch.nn as nn
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

# --- KarmaDock modules (available because /app/KarmaDock is on PYTHONPATH) ---
from utils.fns import set_random_seed, Early_stopper, karmadock_evaluation
from dataset.graph_obj import PDBBindGraphDataset
from dataset.dataloader_obj import PassNoneDataLoader
from architecture.KarmaDock_architecture import KarmaDock

# --- local (same dir): full-schema CSV -> complex-id mapping (prototype + full data) ---
from seminar_csv import complex_ids


# --------------------------------------------------------------------------- #
# Multi-GPU (DistributedDataParallel) helpers.
#
# DDP is OPT-IN and fully transparent: it activates only when the job is launched
# under `torchrun` (which sets WORLD_SIZE>1). With a plain `python3 train.py` the
# code path below is identical to the single-GPU version that trained P2/P3, so
# those results stay reproducible. DDP exists because the full-data from-scratch
# run's train set makes single-GPU wall-time impractical.
#
# Data are sharded by striping the complex-id list per rank (ids[rank::world]),
# which needs no sampler support from KarmaDock's custom PassNoneDataLoader. DDP
# itself all-reduces gradients during backward; we additionally all-reduce the
# scalar metrics so every rank sees identical val numbers and makes the SAME
# early-stop decision. Only rank 0 writes checkpoints, logs, and W&B.
# --------------------------------------------------------------------------- #
def ddp_info():
    """(enabled, rank, local_rank, world_size) from the torchrun environment."""
    world = int(os.environ.get("WORLD_SIZE", "1"))
    if world > 1:
        return True, int(os.environ["RANK"]), int(os.environ.get("LOCAL_RANK", "0")), world
    return False, 0, 0, 1


def shard(ids, rank, world):
    """Stripe a list across ranks so each rank trains on a disjoint subset."""
    return ids[rank::world] if world > 1 else list(ids)


def all_reduce_sum(values, device):
    """Sum a small list of python floats across all ranks; returns a python list."""
    t = torch.tensor(values, dtype=torch.float64, device=device)
    dist.all_reduce(t, op=dist.ReduceOp.SUM)
    return t.tolist()


def parse_args():
    p = argparse.ArgumentParser(description="Retrain / fine-tune KarmaDock.")
    p.add_argument("--graph_dir", required=True,
                   help="Dir with per-complex <id>.dgl graphs (from generate_graph.py).")
    p.add_argument("--val_graph_dir", default="",
                   help="Graph dir for the validation complexes when --val_csv points to a "
                        "separately-preprocessed split (LP train/val live in different dirs). "
                        "Defaults to --graph_dir.")
    p.add_argument("--complex_dir", default="",
                   help="KarmaDock-layout complex dir (only needed if a graph must be regenerated).")
    p.add_argument("--csv", required=True,
                   help="Seminar train CSV (proto_train.csv / full_train.csv / lp_train.csv).")
    p.add_argument("--val_csv", default="",
                   help="Optional explicit validation CSV. If set, ALL of --csv is used "
                        "for training and these complexes for validation -- used for "
                        "LP-PDBBind, whose leak-proof val split must NOT be a random "
                        "carve-out of train. If empty, fall back to a --val_frac split.")
    p.add_argument("--out_dir", required=True,
                   help="Where to write checkpoints and the training log.")
    p.add_argument("--init_model", default="",
                   help="Checkpoint to initialise from. Empty = train from scratch; "
                        "set to karmadock_screening.pkl to fine-tune.")
    p.add_argument("--resume", action="store_true",
                   help="Resume from <out_dir>/last.pt if present (for cluster reschedules).")
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--batch_size", type=int, default=16,
                   help="Physical minibatch size (limited by GPU memory).")
    p.add_argument("--accum_steps", type=int, default=1,
                   help="Gradient-accumulation steps. Effective batch = batch_size*accum_steps. "
                        "Paper uses an effective batch of 64; on a 16 GB V100 use e.g. "
                        "--batch_size 8 --accum_steps 8.")
    p.add_argument("--lr", type=float, default=5e-4)
    p.add_argument("--weight_decay", type=float, default=0.0)
    p.add_argument("--pos_r", type=float, default=1.0,
                   help="Weight on the pose (RMSD) loss vs the MDN scoring loss.")
    p.add_argument("--val_frac", type=float, default=0.1)
    p.add_argument("--patience", type=int, default=20,
                   help="Early-stopping patience (epochs without val improvement).")
    p.add_argument("--num_workers", type=int, default=4)
    p.add_argument("--random_seed", type=int, default=2023)
    p.add_argument("--grad_clip", type=float, default=10.0)
    # Weights & Biases (optional). Key comes from the WANDB_API_KEY env var, never a flag.
    p.add_argument("--wandb", action="store_true", help="log metrics to W&B")
    p.add_argument("--wandb_project", default="karmadock-seminar")
    p.add_argument("--wandb_entity", default=None, help="W&B team/user (optional)")
    p.add_argument("--wandb_run_name", default=None)
    return p.parse_args()


def split_available(ids, graph_dir, val_frac, seed):
    """Keep only ids that actually have a graph, then deterministically split."""
    have = [i for i in ids if os.path.exists(os.path.join(graph_dir, f"{i}.dgl"))]
    missing = len(ids) - len(have)
    if missing:
        print(f"# WARNING: {missing}/{len(ids)} complexes have no .dgl graph "
              f"(rdkit/pocket failures) and are skipped.")
    rng = np.random.RandomState(seed)
    perm = rng.permutation(len(have))
    n_val = max(1, int(round(len(have) * val_frac)))
    val_idx = set(perm[:n_val].tolist())
    train_ids = [have[i] for i in range(len(have)) if i not in val_idx]
    valid_ids = [have[i] for i in range(len(have)) if i in val_idx]
    return train_ids, valid_ids


def available(ids, graph_dir):
    """Keep only ids that actually have a .dgl graph (used with an explicit val CSV)."""
    have = [i for i in ids if os.path.exists(os.path.join(graph_dir, f"{i}.dgl"))]
    missing = len(ids) - len(have)
    if missing:
        print(f"# WARNING: {missing}/{len(ids)} complexes have no .dgl graph and are skipped.")
    return have


def validate_sums(model, loader, device, pos_r):
    """Validation loss SUMS (+count) over a loader -- DDP-friendly (all-reduce the sums).

    Mirrors the loss used in training: loss = pos_r*rmsd_loss + mdn_loss.
    """
    model.eval()
    s_tot = s_rmsd = s_mdn = 0.0
    n = 0
    with torch.no_grad():
        for data in loader:
            if data is None:
                continue
            data = data.to(device)
            rmsd_loss, mdn_loss = model(data, device, pos_r)
            if mdn_loss is None:
                continue
            loss = pos_r * rmsd_loss + mdn_loss
            s_tot += float(loss); s_rmsd += float(rmsd_loss); s_mdn += float(mdn_loss); n += 1
    return s_tot, s_rmsd, s_mdn, n


def maybe_no_sync(model, active):
    """no_sync() context to skip DDP gradient all-reduce on non-boundary accum steps."""
    if active and hasattr(model, "no_sync"):
        return model.no_sync()
    return contextlib.nullcontext()


def build_loader(ids, args, dataset_type, shuffle, graph_dir=None):
    ds = PDBBindGraphDataset(
        src_dir=args.complex_dir,
        pdb_ids=ids,
        dst_dir=graph_dir or args.graph_dir,
        dataset_type=dataset_type,
        n_job=1,
        on_the_fly=True,   # reload each <id>.dgl and re-randomise the start pose per epoch
        verbose=False,
    )
    return PassNoneDataLoader(
        dataset=ds, batch_size=args.batch_size, shuffle=shuffle,
        num_workers=args.num_workers, follow_batch=[], pin_memory=True,
    )


def main():
    args = parse_args()

    # ---- distributed setup (no-op unless launched under torchrun) ----
    is_ddp, rank, local_rank, world = ddp_info()
    main_proc = (rank == 0)
    if is_ddp:
        dist.init_process_group(backend="nccl")
        torch.cuda.set_device(local_rank)
        device = f"cuda:{local_rank}"
    else:
        device = "cuda:0" if torch.cuda.is_available() else "cpu"

    if main_proc:
        os.makedirs(args.out_dir, exist_ok=True)
    if is_ddp:
        dist.barrier()  # ensure out_dir exists before anyone touches it
    set_random_seed(args.random_seed)
    if main_proc:
        print(f"# device: {device} | DDP: {is_ddp} (world_size={world})")

    # ---- Weights & Biases (rank 0 only) ----
    wb = None
    if args.wandb and main_proc:
        try:
            import wandb
            # Credentials come from WANDB_API_KEY or a one-time `wandb login` (~/.netrc, visible
            # via the mounted home). Only force offline if neither exists; then `wandb sync` later.
            has_creds = os.environ.get("WANDB_API_KEY") or os.path.exists(os.path.expanduser("~/.netrc"))
            if not has_creds and os.environ.get("WANDB_MODE") != "offline":
                print("# WARNING: no W&B credentials (WANDB_API_KEY / ~/.netrc) -> forcing offline")
                os.environ["WANDB_MODE"] = "offline"
            eff_batch = args.batch_size * args.accum_steps * world
            stage = "scoring" if args.pos_r == 0 else "docking"
            base = args.wandb_run_name or "kd"
            # W&B run identity: each fresh run gets a unique id, so a re-submitted, failed, or
            # stopped attempt is always its own record and never overwrites a prior run. The id
            # is persisted to <out_dir>/wandb_run_id.txt, and reused only for a genuine reschedule
            # (out_dir still holds last.pt AND that file). Cleaning out_dir starts a new W&B run;
            # keeping it + --resume continues the same one.
            rid_file = os.path.join(args.out_dir, "wandb_run_id.txt")
            if args.resume and os.path.exists(os.path.join(args.out_dir, "last.pt")) and os.path.exists(rid_file):
                run_id = open(rid_file).read().strip()
            else:
                run_id = f"{base}_{int(time.time())}_{os.getpid()}"
                os.makedirs(args.out_dir, exist_ok=True)
                with open(rid_file, "w") as _rf:
                    _rf.write(run_id)
            run_name = (f"{base}_lr{args.lr:g}_bs{eff_batch}_ep{args.epochs}"
                        f"_pat{args.patience}_seed{args.random_seed}_{run_id.rsplit('_', 2)[-1]}")
            cfg = dict(vars(args))
            cfg.update(effective_batch=eff_batch, stage=stage, world_size=world,
                       init_from=("scratch" if not args.init_model else os.path.basename(args.init_model)))
            wb = wandb.init(project=args.wandb_project, entity=args.wandb_entity,
                            id=run_id, name=run_name, config=cfg,
                            dir=args.out_dir, resume="allow")
            print(f"# W&B run: {run_name}")
        except Exception as e:
            print(f"# WARNING: W&B disabled ({e})")
            wb = None

    # ---- data ----
    # If --val_csv is given (LP-PDBBind), use it verbatim as the validation set and ALL of
    # --csv for training -- the leak-proof val split must not be a random carve-out. Else
    # fall back to the deterministic val_frac split used for the prototype pipelines.
    val_graph_dir = args.val_graph_dir or args.graph_dir
    if args.val_csv:
        train_ids = available(complex_ids(args.csv), args.graph_dir)
        valid_ids = available(complex_ids(args.val_csv), val_graph_dir)
    else:
        train_ids, valid_ids = split_available(
            complex_ids(args.csv), args.graph_dir, args.val_frac, args.random_seed)
    if main_proc:
        print(f"# train: {len(train_ids)} | valid: {len(valid_ids)} complexes (global)")
    # shard across DDP ranks (no-op when world==1)
    train_ids = shard(train_ids, rank, world)
    valid_ids = shard(valid_ids, rank, world)
    train_loader = build_loader(train_ids, args, "train", shuffle=True)
    valid_loader = build_loader(valid_ids, args, "valid", shuffle=False, graph_dir=val_graph_dir)

    # ---- model ----
    # Both DataParallel and DistributedDataParallel store params under a 'module.' prefix,
    # so the checkpoint format is identical to the P2/P3 checkpoints inference already reads.
    model = KarmaDock()
    if is_ddp:
        if args.init_model:
            if main_proc:
                print(f"# init weights from {args.init_model}")
            state = torch.load(args.init_model, map_location="cpu")
            sd = {k.replace("module.", "", 1): v for k, v in state["model_state_dict"].items()}
            model.load_state_dict(sd, strict=False)
        model.to(device)
        # find_unused_parameters=True: stage-1 scoring (pos_r=0) skips the EGNN docking
        # branch, leaving those params grad-less -> required so DDP doesn't hang/error.
        model = DDP(model, device_ids=[local_rank], find_unused_parameters=True)
    else:
        model = nn.DataParallel(model, device_ids=[0] if device.startswith("cuda") else None)
        model.to(device)
        if args.init_model:
            print(f"# init weights from {args.init_model}")
            state = torch.load(args.init_model, map_location=device)
            model.load_state_dict(state["model_state_dict"], strict=False)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr,
                                 weight_decay=args.weight_decay)

    best_ckpt = os.path.join(args.out_dir, "karmadock_team002.pkl")
    last_ckpt = os.path.join(args.out_dir, "last.pt")
    # Single-process keeps the proven upstream Early_stopper. DDP uses a tiny manual tracker
    # so every rank makes the identical stop decision off the all-reduced val loss while
    # only rank 0 writes files (avoids checkpoint write races).
    stopper = None if is_ddp else Early_stopper(model_file=best_ckpt, mode="lower", patience=args.patience)
    best_val = None
    bad_epochs = 0

    start_epoch = 0
    if args.resume and os.path.exists(last_ckpt):
        ck = torch.load(last_ckpt, map_location=device)
        model.load_state_dict(ck["model_state_dict"], strict=True)
        optimizer.load_state_dict(ck["optimizer_state_dict"])
        start_epoch = ck["epoch"] + 1
        best_val = ck.get("best_score", None)
        bad_epochs = ck.get("bad_epochs", 0)
        if stopper is not None:
            stopper.best_score = best_val
        if main_proc:
            print(f"# resumed from {last_ckpt} at epoch {start_epoch}")

    log_path = os.path.join(args.out_dir, "train_log.csv")
    if start_epoch == 0 and main_proc:
        with open(log_path, "w") as f:
            f.write("epoch,train_loss,train_rmsd,train_mdn,val_loss,val_rmsd,val_mdn,seconds\n")

    # ---- training loop ----
    for epoch in range(start_epoch, args.epochs):
        t0 = time.perf_counter()
        model.train()
        tr_tot, tr_rmsd, tr_mdn, n = 0.0, 0.0, 0.0, 0
        # Gradient accumulation: step the optimizer every accum_steps minibatches so the
        # effective batch = batch_size*accum_steps (paper: 64) even if a single batch must
        # stay small to fit GPU memory. Under DDP the all-reduce of gradients is skipped on
        # non-boundary micro-steps (no_sync) so accumulation stays bandwidth-efficient.
        optimizer.zero_grad()
        accum = 0
        for data in train_loader:
            if data is None:
                continue
            data = data.to(device)
            rmsd_loss, mdn_loss = model(data, device, args.pos_r)
            if mdn_loss is None:
                continue
            loss = args.pos_r * rmsd_loss + mdn_loss
            boundary = ((accum + 1) % args.accum_steps == 0)
            with maybe_no_sync(model, is_ddp and not boundary):
                (loss / args.accum_steps).backward()
            accum += 1
            if accum % args.accum_steps == 0:
                if args.grad_clip > 0:
                    nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                optimizer.step()
                optimizer.zero_grad()
            tr_tot += float(loss); tr_rmsd += float(rmsd_loss); tr_mdn += float(mdn_loss); n += 1
        # flush any leftover gradients from a partial accumulation window
        if accum % args.accum_steps != 0:
            if args.grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()
            optimizer.zero_grad()

        # ---- validation ----
        if is_ddp:
            # local sums -> all-reduce so every rank shares the same global means
            s = list(validate_sums(model, valid_loader, device, args.pos_r))
            tr_tot, tr_rmsd, tr_mdn, n, s0, s1, s2, vn = all_reduce_sum(
                [tr_tot, tr_rmsd, tr_mdn, n, s[0], s[1], s[2], s[3]], device)
            n = max(n, 1); vn = max(vn, 1)
            tr_tot, tr_rmsd, tr_mdn = tr_tot / n, tr_rmsd / n, tr_mdn / n
            val_loss, val_rmsd, val_mdn = s0 / vn, s1 / vn, s2 / vn
        else:
            n = max(n, 1)
            tr_tot, tr_rmsd, tr_mdn = tr_tot / n, tr_rmsd / n, tr_mdn / n
            v_tot, v_rmsd, v_mdn = karmadock_evaluation(model, valid_loader, device, args.pos_r)
            val_loss = float(v_tot.mean()); val_rmsd = float(v_rmsd.mean()); val_mdn = float(v_mdn.mean())
        secs = time.perf_counter() - t0

        if main_proc:
            print(f"[epoch {epoch:03d}] train {tr_tot:.3f} (rmsd {tr_rmsd:.3f}/mdn {tr_mdn:.3f}) | "
                  f"val {val_loss:.3f} (rmsd {val_rmsd:.3f}/mdn {val_mdn:.3f}) | {secs:.0f}s")
            with open(log_path, "a") as f:
                f.write(f"{epoch},{tr_tot:.5f},{tr_rmsd:.5f},{tr_mdn:.5f},"
                        f"{val_loss:.5f},{val_rmsd:.5f},{val_mdn:.5f},{secs:.1f}\n")
            if wb is not None:
                wb.log({"epoch": epoch, "lr": optimizer.param_groups[0]["lr"],
                        "train/loss": tr_tot, "train/rmsd": tr_rmsd, "train/mdn": tr_mdn,
                        "val/loss": val_loss, "val/rmsd": val_rmsd, "val/mdn": val_mdn,
                        "epoch_seconds": secs}, step=epoch)

        # ---- checkpoint + early stopping ----
        if is_ddp:
            # every rank shares val_loss, so all reach the same decision in lockstep;
            # only rank 0 writes the files.
            improved = (best_val is None) or (val_loss < best_val)
            if improved:
                best_val = val_loss; bad_epochs = 0
            else:
                bad_epochs += 1
            if main_proc:
                if improved:
                    torch.save({"model_state_dict": model.state_dict()}, best_ckpt)
                torch.save({"epoch": epoch, "model_state_dict": model.state_dict(),
                            "optimizer_state_dict": optimizer.state_dict(),
                            "best_score": best_val, "bad_epochs": bad_epochs}, last_ckpt)
            if bad_epochs >= args.patience:
                if main_proc:
                    print(f"# early stopping at epoch {epoch}")
                break
        else:
            stopper.step(val_loss, model)
            best_val = stopper.best_score
            torch.save({"epoch": epoch,
                        "model_state_dict": model.state_dict(),
                        "optimizer_state_dict": optimizer.state_dict(),
                        "best_score": stopper.best_score}, last_ckpt)
            if stopper.early_stop:
                print(f"# early stopping at epoch {epoch}")
                break

    if wb is not None:
        wb.summary["best_val_loss"] = float(best_val) if best_val is not None else None
        try:
            art = __import__("wandb").Artifact("karmadock_team002", type="model")
            art.add_file(best_ckpt)
            wb.log_artifact(art)
        except Exception as e:
            print(f"# W&B artifact upload skipped ({e})")
        wb.finish()
    if is_ddp:
        dist.barrier()
        dist.destroy_process_group()
    if main_proc:
        print(f"# done. best checkpoint: {best_ckpt}")


if __name__ == "__main__":
    main()
