universe = docker
docker_image = docker.io/dhanya24/diffdock-pocket-fixed:v8

executable = /home/bdldt_team005/DLDockingBenchSeminar/training/run_training_full.sh

output = /home/bdldt_team005/DLDockingBenchSeminar/training/logs/training_full.out
error  = /home/bdldt_team005/DLDockingBenchSeminar/training/logs/training_full.err
log    = /home/bdldt_team005/DLDockingBenchSeminar/training/logs/training_full.log

request_GPUs   = 1
request_CPUs   = 8
request_memory = 48GB
request_disk   = 60GB

requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
Rank = (CUDADeviceName == "A100-SXM4-80GB")

queue
