universe = docker
docker_image = docker.io/elab00003/unimol:1
executable = /home/bdldt_team007/DLDockingBenchSeminar/run_pkl_to_sdf.sh
output = /home/bdldt_team007/DLDockingBenchSeminar/logs/pkl_to_sdf.out
error  = /home/bdldt_team007/DLDockingBenchSeminar/logs/pkl_to_sdf.err
log    = /home/bdldt_team007/DLDockingBenchSeminar/logs/pkl_to_sdf.log
should_transfer_files = NO
request_GPUs = 0
request_CPUs = 2
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
