universe = docker
docker_image = docker.io/elab00003/unimol:1
executable = /home/bdldt_team007/DLDockingBenchSeminar/run_infer.sh
output = /home/bdldt_team007/DLDockingBenchSeminar/logs/infer.out
error  = /home/bdldt_team007/DLDockingBenchSeminar/logs/infer.err
log    = /home/bdldt_team007/DLDockingBenchSeminar/logs/infer.log
should_transfer_files = NO
request_GPUs = 1
request_CPUs = 8
request_memory = 32G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
