universe = docker
docker_image = docker.io/elab00003/unimol:1
executable = /home/bdldt_team007/DLDockingBenchSeminar/run_preprocess.sh
output = /home/bdldt_team007/DLDockingBenchSeminar/logs/preprocess.out
error  = /home/bdldt_team007/DLDockingBenchSeminar/logs/preprocess.err
log    = /home/bdldt_team007/DLDockingBenchSeminar/logs/preprocess.log
should_transfer_files = NO
request_GPUs = 0
request_CPUs = 4
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
