universe = docker
docker_image = docker.io/dhanya24/diffdock-pocket-fixed:v8
environment = "CUDA_LAUNCH_BLOCKING=1"
executable = /home/bdldt_team005/DLDockingBenchSeminar/inference/run_inference_posebusters.sh
output = /home/bdldt_team005/DLDockingBenchSeminar/inference/logs/inference_posebusters.out
error = /home/bdldt_team005/DLDockingBenchSeminar/inference/logs/inference_posebusters.err
log = /home/bdldt_team005/DLDockingBenchSeminar/inference/logs/inference_posebusters.log
request_GPUs = 1
request_CPUs = 4
request_memory = 32GB
request_disk = 20GB
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
